version: '3'

services:
  frontend:
    build:
      context: ./my-app
    ports:
      - "9000:3000"

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - database

  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: ver
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - ./ver.sql:/docker-entrypoint-initdb.d/ver.sql

# bigquery:
#    image: gcr.io/cloudsql-docker/gce-proxy:latest
#    command: ["/cloud_sql_proxy", "--dir=/cloudsql", "-instances=your:project:connection-name=tcp:3307", "-credential_file=/secrets/cloudsql/credentials.json"]
#    volumes:
#      - ./app/key.json.json:/secrets/cloudsql/credentials.json
#    ports:
#      - "3307:3307"
